name: Build

on:
  workflow_dispatch:
  push:
    branches: ['*']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.12.1
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Bootstrap
        run: bash bootstrap.sh
      - run: pnpm i --frozen-lockfile
      - name: Build frontend
        run: pnpm run build:production
      - name: Generate npm tarball
        run: |
          pnpm pack
          tar -xvzf compass-web-*.tgz
      - name: Upload tarball
        uses: actions/upload-pages-artifact@v3
        with:
          name: compass-web
          path: package
