name: Build

on:
  workflow_dispatch:
  push:
    branches: ['*']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.15.4
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/configure-pages@v5
      - run: pnpm i --frozen-lockfile
      - name: Bootstrap
        run: bash bootstrap.sh
      - name: Build frontend
        run: npm run build:production
      - name: Generate npm tarball
        run: |
          npm pack
          tar -xvzf compass-web-*.tgz
      - name: Deploy to Netlify
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Upload tarball
        uses: actions/upload-pages-artifact@v3
        with:
          name: compass-web
          path: package
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        id: deployment
        uses: actions/deploy-pages@v4
