name: Publish compass-web to npm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        required: false
        default: "latest"

jobs:
  publish-npm:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.12.1
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Check version
        id: check-version
        run: |
          version=$(node -e "console.log(require('./package.json').version);")

          if pnpm view "compass-web@$version" version > /dev/null 2>&1; then
            echo "compass-web@$version already exists on npm"
            exit 1
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT

          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi
      - name: Bootstrap
        run: bash bootstrap.sh
      - run: pnpm i --frozen-lockfile
      - name: Build compass-web
        run: NODE_ENV=production pnpm run build:production
      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm publish --tag ${{ github.event.inputs.tag }} --no-git-checks --access public
