name: Publish compass-web to Docker Hub

on:
  workflow_dispatch:

jobs:
  publish-docker:
    needs:
      - publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Check version
        id: check-version
        run: |
          version=$(node -e "console.log(require('./package.json').version);")

          if ! npm view "compass-web@$version" version > /dev/null 2>&1; then
            echo "npm package compass-web@$version doesn't exist"
            exit 1
          fi

          if curl --silent --fail "https://registry.hub.docker.com/v2/repositories/haohanyang/compass-web/tags/$version/" > /dev/null; then
            echo "image haohanyang/compass-web:$version" already exists
            exit 1
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT

          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: haohanyang
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ steps.check-version.outputs.is_latest != 'true' }}
        with:
          push: true
          tags: haohanyang/compass-web:${{ steps.check-version.outputs.version }}
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          build-args: COMPASS_WEB_VERSION=${{ steps.check-version.outputs.version }}
      - name: Build and push with latest tag
        uses: docker/build-push-action@v6
        if: ${{ steps.check-version.outputs.is_latest == 'true' }}
        with:
          push: true
          tags: haohanyang/compass-web:${{ steps.check-version.outputs.version }},haohanyang/compass-web:latest
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          build-args: COMPASS_WEB_VERSION=${{ steps.check-version.outputs.version }}
