name: Publish compass-web to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to publish (defaults to version in package.json)"
        required: false
        default: ""
        type: string

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.version != '' }}
        with:
          ref: "v${{ github.event.inputs.version }}"
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.version == '' }}
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Check version and detect channel
        id: check-version
        run: |
          version=$(node -e "console.log(require('./package.json').version);")

          if ! npm view "compass-web@$version" version > /dev/null 2>&1; then
            echo "npm package compass-web@$version doesn't exist"
            exit 1
          fi

          if curl --silent --fail "https://registry.hub.docker.com/v2/repositories/haohanyang/compass-web/tags/$version/" > /dev/null; then
            echo "image haohanyang/compass-web:$version already exists"
            exit 1
          fi

          if [[ "$version" == *"-alpha"* ]]; then
            channel="alpha"
          elif [[ "$version" == *"-beta"* ]]; then
            channel="beta"
          elif [[ "$version" == *"-rc"* ]]; then
            channel="rc"
          else
            channel="latest"
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "channel=${channel}" >> $GITHUB_OUTPUT
          echo "Detected version=${version}, channel=${channel}"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: haohanyang
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: haohanyang/compass-web:${{ steps.check-version.outputs.version }},haohanyang/compass-web:${{ steps.check-version.outputs.channel }}
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          build-args: COMPASS_WEB_VERSION=${{ steps.check-version.outputs.version }}
